# name: debugger-action
# on:
#   workflow_dispatch:
# jobs:
#   build:
#     runs-on: ubuntu-latest
#     steps:
#       - uses: actions/checkout@v2
#       - name: Setup Debug Session
#         uses: csexton/debugger-action@master

name: telegram message
on:
  workflow_dispatch:
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      # - uses: actions/checkout@master
      - name: Checkout
        uses: actions/checkout@main

      - uses: appleboy/telegram-action@master
      - name: send message file
        with:
          to: ${{ secrets.TELEGRAM_CHAT_ID }}
          token: ${{ secrets.TELEGRAM_BOT_TOKEN }}
          message_file: tests/message.txt

